version: '3.7'

services:
  server:
    build: "./"
    image: "${IMAGE_NAME}:${IMAGE_VERSION}"
    env_file:
     - .env
    ports:
      - "1070:3000"
    restart: on-failure
    environment:
      APP_PORT: 3000 

      APP_BASE_URL: "http://localhost:1070/"

      DB_HOST: "172.17.42.1"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASS: ""
      DATABASE: "db_surveyapp"